Summary text improvement
MannLabs/OmicLearn pull request #12
Opened 2023-04-01 15:33 UTC by furkanmtorun

Hi Max,

In this PR, I fixed the few issues addressed in #4 .
- Added "," comma between parameters
- Added xgboost version to the text
- Fixed the imputation mistake

<img width="734" alt="Screenshot 2023-04-01 at 17 32 07" src="https://user-images.githubusercontent.com/49681382/229298695-d2d3ae7a-4d83-4082-b305-ec6ef6496c63.png">

2023-04-03 10:34 UTC, straussmaximilian requested changes
Would suggest to change as suggested.

2023-04-03 10:34 UTC, straussmaximilian commented on omiclearn/utils/ui_components.py
> +            text += f"To impute missing values, a {state.missing_value}-imputation strategy is used. "
We used past tense before, so this should also be past tense (was used)

2023-04-03 10:34 UTC, straussmaximilian commented on omiclearn/utils/ui_components.py
> +            text += "Even though dataset contained missing values; no imputation was performed. "
"Even though" puts things into contrast and one could understand this as one should have chosen missing value impoutation.

Suggestion to be more neutral sounding: "Missing values were not imputed."

2023-04-03 10:34 UTC, straussmaximilian commented on omiclearn/utils/ui_components.py
> +        text += f"Features were selected using a {state.feature_method} (n_trees={state.n_trees}) strategy with the maximum number of {state.max_features} features. "
"... with **a** maximum number of"

2023-04-03 10:34 UTC, straussmaximilian commented on omiclearn/utils/ui_components.py
> +        text += f"Features were selected using a {state.feature_method} strategy with the maximum number of {state.max_features} features. "
"... with **a** maximum number of"

2023-04-03 10:34 UTC, straussmaximilian commented on omiclearn/utils/ui_components.py
> +        text += f"For classification, we used a {state.classifier}-Classifier (version: {report['xgboost_version']}, {', '.join(params)}). "
Before that we used passive voice and no pronouns ("we"), I would keept his and be consistent:

"... we used an XGBoost classifier"

2023-04-03 15:46 UTC, furkanmtorun commented on omiclearn/utils/ui_components.py
> +            text += f"To impute missing values, a {state.missing_value}-imputation strategy is used. "
Now, changed.

2023-04-03 15:46 UTC, furkanmtorun commented on omiclearn/utils/ui_components.py
> +            text += "Even though dataset contained missing values; no imputation was performed. "
Really great point! Thank you very much. Changed now

2023-04-03 15:51 UTC, furkanmtorun commented on omiclearn/utils/ui_components.py
> +        text += f"Features were selected using a {state.feature_method} (n_trees={state.n_trees}) strategy with the maximum number of {state.max_features} features. "
Typical grammar mistake for me 😸 Fixed

2023-04-03 15:51 UTC, furkanmtorun commented on omiclearn/utils/ui_components.py
> +        text += f"Features were selected using a {state.feature_method} strategy with the maximum number of {state.max_features} features. "
fixed :)

2023-04-03 15:52 UTC, furkanmtorun commented on omiclearn/utils/ui_components.py
> +        text += f"For classification, we used a {state.classifier}-Classifier (version: {report['xgboost_version']}, {', '.join(params)}). "
Good catch! Fixed now

```python
if state.classifier == "XGBoost":
        text += f"For classification, {state.classifier}-Classifier (version: {report['xgboost_version']}, {', '.join(params)}) was used. "
    else:
        text += f"For classification, {state.classifier}-Classifier ({', '.join(params)}) was used. "
```

2023-04-04 14:32 UTC, straussmaximilian approved these changes
LGTM

2023-04-05 07:32 UTC, merged